

production:
  adapter: mysql2
  database: quidpxyd_noels
  socket: /var/lib/mysql/mysql.sock
  username: quidpxyd_noel
  password: "Palekaka!.com1"
  encoding: utf8

development:
  adapter: mysql2
  database: quidpxyd_noels
  host: localhost
  username: quidpxyd_noel
  password: "Palekaka!.com1"
  encoding: utf8

test:
  adapter: mysql2
  database: quidpxyd_noels
  host: localhost
  username: quidpxyd_noel
  password: "Palekaka!.com1"
  encoding: utf8
